global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'openwrt-wifi'
    scrape_interval: 10s
    static_configs:
      - targets: ['wifi.lan:9100']
  - job_name: 'openwrt-emon'
    scrape_interval: 10s
    static_configs:
      - targets: ['emon.lan:9100']
  - job_name: 'openwrt-link'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.27.1:9100']